### PR TITLE
Update emu2413

### PR DESCRIPTION
**Pull request by okaxaki**
This pull-request updates emu2413 core to the latest [v1.2.7](https://github.com/digital-sound-antiques/emu2413/blob/master/CHANGELOG.md).

Since this pull request drastically improves emu2413's emulation quality, I would appreciate if you consider merging this.  However, I know that VGMPlay is in maintenance phase so I don't mind if it takes time or being rejected in some reason:) 

If I need to fix/check/explain more, let me know please.

[Notes] 
- The new emu2413 has own windowed-sinc sample rate converter but I disabled it to respect the existing VGMPlay’s internal rate converter (More precisely, if 49715 or 49716Hz is given as the sampling rate, emu2413's rate converter will be disabled).
- 512-level panning extension (which was realized as a patch for the original core) is not implemented. I  redirected it to the 3-level, i.e. Left-Center-Right panning.

[Build Check]
I have checked to build VGMPlay with the following environments.
- Windows 10 (Visual Studio 2010, 2015 and 2019)
- macOS 10 Catalina
- Ubuntu 18.04

[in_vgm]
This pull-request does not contain a patch for in_vgm but I locally confirmed to build on VS2015/2019 with the following changes:
- Open in_vgm.dsw and add opll.c and opll.h to the workspace.
- Add  `ucrt.lib` , `vcruntime.lib` and `legacy_stdio_definitions.lib` to Linker->Input->Additional Dependencies.
- Change Linker->Advanced->Image Has Safe Exception Handlers to `No (/SAFESHE:NO)`.

I could not build with VS2010 since VS2010 failed to convert in_vgm.dsw.

Thanks,

### CODE REVIEW

**Comment by superctr** [comment]
It looks good to me. As for in_vgm, it is usually only compiled with Visual C++ 6.0 AFAIK.

**Comment by okaxaki** [comment]
Thanks for checking this. I'm sorry that i currently do not have Visual C++ 6.0 ... (this is a reason why i could not create patch for in_vgm.dsw).

**Comment by ValleyBell** [comment]
Thanks a lot for the PR!

Sorry for the long delay. I merged it and made a few changes to fix the VC6 build, which was broken since the NukedOPLL PR.

I also restored smooth channel panning (I hope you don't mind) and even noticed a bug with channel assignment that was there for years.

**Comment by okaxaki** [comment]
Thanks for mergning this and additional changes. I will import the smooth panning feature to emu2413 when I update next time.

**Pull request merged**
