### PR TITLE
Nuked OPM 0.9 beta

### PR DESCRIPTION
**Pull request by nukeykt**

### CODE REVIEW

**Comment by superctr** [comment]
Looks good to me. Just a small thing, I would prefer if the `%` were changed to `&` for speed reasons.

**Comment by nukeykt** [comment]
I think compiler will optimize it to & 31 (even in debug build) because I use unsigned integer. But I don't mind this change.

**Comment by nukeykt** [comment]
yeah, at very least visual studio optimizes it to `&` in all builds

**Comment by superctr** [comment]
We still build with Visual C++ 6 from 1998. It doesn't do all the optimizations that modern compilers do, so I think it's good to include it in the code.

**Comment by ValleyBell** [comment]
Looks good to me.

btw: For `uint % 32`, MSVC6 uses `mov ecx,20h / div eax,ecx` in Debug mode and `and ecx,1Fh` in Release mode.

**Comment by nukeykt** [comment]
Interesting, dos era version of watcom compiler did this optimization in debug mode, so I assumed other compilers would do this as well

**Comment by ValleyBell** [comment]
Debug mode really is not something *I* would optimize for, though. As long as it performs well in Release mode, that's fine to me.

**Pull request merged**
